sudo: false
language: cpp
compiler:
- gcc
os:
- linux
before_install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:	
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
install:
- make set_environ_vars.sh && `cat set_environ_vars.sh`
- make
- make MODE=clang
