sudo: false
language: cpp
compiler:
- gcc
os:
- linux
before_install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:	
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - gcc-4.8
    - g++-4.8
    - libhdf5-serial-dev
    - libboost1.55-all-dev
install:
- make
- make MODE=clang
